### ISSUE TITLE
你好！可不可以适配下新版idea

### ISSUE THREAD

**Issue by kecikeci** [cong1223/intellij-plugin-yapi2ts#1]
感谢大佬开发插件，可不可以适配下新版，感谢

![image](https://user-images.githubusercontent.com/32811349/208296106-0cc43b76-d8a7-4dc7-af24-0bcebd4bb0e0.png)

**Comment by cong1223** [comment]
嗯，适配新版本idea的工作已经提上日程

**Comment by kecikeci** [comment]
> 嗯，适配新版本idea的工作已经提上日程

感谢大佬

**Comment by cong1223** [comment]
> > 嗯，适配新版本idea的工作已经提上日程
> 
> 感谢大佬

done
